### ISSUE TITLE
Indexierung klappt nicht zu 100% / einige Artikel und Datenbankspalten werden nicht indexiert

### ISSUE THREAD

**Issue by Ds-2014** [xong/rexsearch#13]
Hey,

ich bräuchte ein bisschen Hilfe.

Die Indexierung lässt bei mir verschiedene Artikel aus, bzw. ich bekomme keine Ausgabe. Nehmen wir an ich habe einen Artikel mit dem Namen "Dr. Max Mustermann". In dem Artikel ist sein CV als Text hinterlegt. Wenn ich nun nach "Mustermann" suche, kommt kein Hinweis auf den CV... Auf andere Unterseiten, zb. Impressum, aber schon. 

Außerdem stoppt bei mir die Indexierung, sobald ich in den Einstellungen Datenbank-Spalten aufnehmen möchte :(

Redaxo 4.6.0
REXSearch 0.7.8

Was kann ich tun?

Danke, lg Ds

**Comment by alexplusde** [comment]
Hey Ds,

schade, dass dein Issue hier untergegangen ist. Hast du das Problem noch gelöst bekommen?
