### ISSUE TITLE
Statistik: Statistik-Bilder werden nicht dargestellt

### ISSUE THREAD

**Issue by alexplusde** [xong/rexsearch#20]
Ist bei mir bei allen Installationen schon seit längerer Zeit so, aber habe erst jetzt mal genauer nachgesehen: Das Bild wird generiert und wenn man es abspeichert, dann wird es auch geöffnet.

Am Header kann's eigentlich auch nicht liegen, denn es wird ordentlich als image/png ausgegeben:
```
200 OK
Pragma: no-cache
Date: Mon, 02 Nov 2015 09:18:16 GMT
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
Server: Apache/2.4.10
X-Powered-By: PHP/5.4.30
Transfer-Encoding: chunked
Content-Type: image/png
Cache-Control: no-store, no-cache, must-revalidate, pre-check=0, post-check=0, max-age=0
Connection: close
Expires: Mon, 26 Jul 1997 05:00:00 GMT
```

Schon mal das Phänomen gehabt?

**Comment by xong** [comment]
Ich muss gestehen, ich hab RexSearch schon seit fast zwei Jahren nicht mehr richtig eingesetzt.
Kannst du mir einen Zugang zu einem Server geben, auf dem das Problem auftritt?

**Comment by alexplusde** [comment]
Was brauchst du, FTP & Backend?

**Comment by xong** [comment]
Zumindest erstmal Backend. FTP schadet nie. =)

**Comment by alexplusde** [comment]
Mail mit Backend-Zugangsdaten ist unterwegs, FTP kann ich erst in ein paar Tagen nachliefern.

**Comment by xong** [comment]
Also entweder werden bei der Generierung der Skripte Fehlermeldungen ausgegeben, die dann den Bildcode verwursten oder da ist noch was anderes faul.
Versuch einfach mal testhalber, die Fehlerausgabe zu unterdrücken.

**Comment by alexplusde** [comment]
Hm, interessant: Ich habe bei dem gleichen Hoster (DF) noch mal eine Website liegen und schnell RexSearch installiert: Da funktioniert die Generierung fehlerfrei (gleiche PHP-Version wie Problem-Installation eingestellt, und display_errors aktiviert)

Auf die PHP.ini bei der betroffenen Installation habe ich jedoch im Moment keinen Zugriff. Ich werde den Reseller vom Kunden fragen, ob er display_errors abschaltet, die 5.6-PHP aktiviert und mich melden.

**Comment by xong** [comment]
Mir würde erstmal reichen, wenn du die Fehlermeldungen, die ausgegeben werden, überprüfst.
Falls es überhaupt Fehlermeldungen sind. Wenn ich mir die HTTP-Antwort vom Server anschaue, scheint es so, als wären da einfach nur eine paar Leerzeilen, die vor den Bilddaten ausgegeben werden.

**Comment by staabm** [comment]
ggf. hast du irgendwo ein addon/plugin aktiv welches vor `<?php` oder nach `?>` leerzeilen enthält

**Comment by alexplusde** [comment]
@staabm Das war korrekt. Das betroffene Skript habe ich gerade ausfindig gemacht, es war via addcode-Addon eingebunden. Nun sind die Leerzeilen weg, Das Problem aber noch da.

Als nächstes habe ich die PNGs mal vergleichsweise in Notepad++ geöffnet: Das, das korrekt angezeigt wird, wurde in ANSI ausgeliefert. Das, das nicht korrekt angezeigt wird, als UTF-8 (obwohl die Datei selbst ANSI-Code ist). Wenn ich die Kodierung auf ANSI ändere und abspeichere, wird sie korrekt angezeigt. Ich denke, das wird letztendliche der Grund sein.

Jetzt ist die Frage natürlich: Warum passiert das?

**Comment by staabm** [comment]
Dann schickt dir noch irgendein code nen http header zwischenrein

**Comment by alexplusde** [comment]
@staabm Danke, ich mache mich mal auf die Suche. Bin mir inzwischen sicher, dass es daran wohl liegen muss.
