### ISSUE TITLE
Wunsch: Indizierung per Cronjob

### ISSUE THREAD

**Issue by skerbis** [xong/rexsearch#26]
Das wäre genial.

**Comment by staabm** [comment]
Meinst du hier via cronjob addon oder einem richtigen linux cron (cron.d)

**Comment by skerbis** [comment]
cron.d würde ich bevorzugen.

**Comment by skerbis** [comment]
Muss aber nicht unbedingt mehr für Redaxo 4 realisiert werden.

**Comment by AWqxKAWERbXo** [comment]
![image](https://cloud.githubusercontent.com/assets/3855487/14737584/0e5cfe6a-087d-11e6-9f40-e14ae2871148.png)

```
<?php

$xsearch = new RexSearch;

$xsearch->indexColumn('rex_article', 'seo_description', 'id');
$xsearch->indexColumn('rex_article', 'seo_keywords', 'id');
$xsearch->indexColumn('rex_xf_charts', 'title', 'id');
$xsearch->indexColumn('rex_xf_charts', 'interpret', 'id');

?>
```

**Comment by staabm** [comment]
Darf man fragen wie sich Eure Inhalte ändern, sodass eine manuelle re-indizierung nötig ist? Normalerweise würde das addon ja selbstständig den index aktualisieren wenn man via Backend ändert...

**Comment by skerbis** [comment]
@staabm Es gibt noch andere Dinge, die indiziert werden müssen als nur Artikel und Slices. PDFs, (x/y)form-Tabellen etc. die werden wohl anscheinend nicht beachtet, wenn neue Inhalte hinzugefügt werden. Ein Cron kann das erledigen.

**Comment by AWqxKAWERbXo** [comment]
@skerbis +1

In meinem Beispiel oben habe ich xform im Backend dazu benutzt, um eine Übersicht aller SEO42-Description und -Keywords-Felder aus der rex_article zu listen und zu bearbeiten. Ist sicherlich nicht so gedacht, hat aber sehr gut funktioniert.

Desweiteren kann der Kunde in der Charts-Tabelle via xform selbständig Datensätze ändern, die dann in aller Regelmäßigkeit auch von der Suche indiziert werden sollen, ohne, dass er das manuell anstoßen muss.

Was jetzt blöd ist: Wenn der Kunde sich einloggt, dauert die erste Seite nach dem Login etwa. 10 Sekunden, weil erst noch Cronjobs ausgeführt werden müssen. Das gezielte Anstoßen außerhalb über das Frontend, bspw. über einen GET-Parameter oder eine extra URL via Webcron, hätte immense Vorteile.
